import { Activity, ArrowRight, CalendarDays, CheckCircle2, Clock3, Droplets, FileText, HeartPulse, History, Moon, Sparkles, Stethoscope, UserRound, Utensils } from "lucide-react";

const fallbackPatient = { name: "Rahul Patel", age: 32, gender: "Male", chiefComplaint: "Digestive discomfort", duration: "5 days", severity: 6, triage: { level: "Moderate" }, prakriti: "Pitta", agni: "Variable", koshtha: "Regular", registeredAt: "Today" };

function StatCard({ icon: Icon, label, value, note }) {
  return <div className="patient-stat-card"><div className="patient-stat-icon"><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div></div>;
}
function ProgressBar({ value }) { return <div className="patient-progress"><span style={{ width: `${value}%` }} /></div>; }

export default function PatientDashboard({ patientCase, patientCases = [], onStartAssessment, onViewHistory, onOpenDoctor, onOpenProfile, onBookAppointment, onOpenTreatment }) {
  const patient = patientCase?.name ? patientCase : fallbackPatient;
  const history = patient.profileId
    ? patientCases.filter((item) => item.name && item.id && item.profileId === patient.profileId).slice(0, 4)
    : patientCases.filter((item) => item.name && item.id).slice(0, 4);
  const triage = patient.triage?.level || (patient.severity >= 7 ? "High" : "Moderate");
  const triageClass = triage.toLowerCase();
  return (
    <div className="patient-dashboard-page"><div className="patient-dashboard-shell">
      <section className="patient-welcome-card"><div><div className="patient-eyebrow"><Sparkles size={15} /> YOUR HEALTH DASHBOARD</div><h1>Good morning, {patient.name || "there"} 👋</h1><p>Here is a simple view of your health information, recent assessment, and next steps.</p><div className="patient-profile-line"><span><UserRound size={15} /> {patient.age || 32} years</span><span><Activity size={15} /> {patient.gender || "Patient"}</span><span><Clock3 size={15} /> Last update: {patient.registeredAt || "Today"}</span>{patient.profileId && <span>Profile: {patient.profileId}</span>}</div></div><div className="patient-welcome-icon"><HeartPulse size={42} /></div></section>
      <div className="patient-dashboard-grid"><main>
        <section className="patient-section-heading"><div><span className="patient-section-kicker">OVERVIEW</span><h2>Your health today</h2></div><button className="patient-link-button" onClick={onStartAssessment}>New assessment <ArrowRight size={16} /></button></section>
        <div className="patient-stats-grid"><StatCard icon={Droplets} label="Water" value="4 / 8 glasses" note="Keep going today" /><StatCard icon={Moon} label="Sleep" value="7h 20m" note="Good sleep target" /><StatCard icon={Activity} label="Activity" value="5,200 steps" note="Daily movement" /><StatCard icon={Utensils} label="Meals" value="2 / 3" note="Dinner still pending" /></div>
        <section className="patient-panel patient-assessment-panel"><div className="patient-panel-header"><div><span className="patient-section-kicker">LATEST ASSESSMENT</span><h3>{patient.chiefComplaint || "Health assessment"}</h3></div><span className={`patient-status-pill ${triageClass}`}>{triage} priority</span></div><div className="patient-assessment-summary"><div className="patient-score"><strong>{patient.severity || 6}<small>/10</small></strong><span>Symptom severity</span></div><div className="patient-summary-details"><div><span>Duration</span><strong>{patient.duration || "Not recorded"}</strong></div><div><span>Body type</span><strong>{patient.prakriti || "Not recorded"}</strong></div><div><span>Digestion</span><strong>{patient.agni || "Not recorded"}</strong></div><div><span>Bowel pattern</span><strong>{patient.koshtha || "Not recorded"}</strong></div></div></div><div className="patient-assessment-note"><CheckCircle2 size={17} /><span>Your information has been added to your case summary for the healthcare professional.</span></div></section>
        <section className="patient-panel"><div className="patient-panel-header"><div><span className="patient-section-kicker">YOUR PLAN</span><h3>Small steps for today</h3></div><Sparkles size={20} className="patient-panel-spark" /></div><div className="patient-plan-list"><div className="patient-plan-item"><div className="patient-plan-icon"><Droplets size={18} /></div><div><strong>Drink more water</strong><p>Try to reach 8 glasses through the day.</p><ProgressBar value={50} /></div><span>4/8</span></div><div className="patient-plan-item"><div className="patient-plan-icon"><Activity size={18} /></div><div><strong>Take a short walk</strong><p>A light 15–20 minute walk can support daily activity.</p></div><span>Next</span></div><div className="patient-plan-item"><div className="patient-plan-icon"><Moon size={18} /></div><div><strong>Keep a regular sleep time</strong><p>Aim for 7–8 hours tonight.</p></div><span>Tonight</span></div></div><p className="patient-disclaimer">General wellness suggestions only. They do not replace advice from a qualified healthcare professional.</p></section>
      </main><aside>
        <section className="patient-panel patient-quick-panel"><span className="patient-section-kicker">QUICK ACTIONS</span><h3>What would you like to do?</h3><button className="patient-action-card" onClick={onStartAssessment}><div className="patient-action-icon"><Activity size={19} /></div><div><strong>Start health assessment</strong><span>Record new symptoms</span></div><ArrowRight size={17} /></button><button className="patient-action-card" onClick={onOpenProfile}><div className="patient-action-icon"><UserRound size={19} /></div><div><strong>View my profile</strong><span>Personal and health details</span></div><ArrowRight size={17} /></button><button className="patient-action-card" onClick={onViewHistory}><div className="patient-action-icon"><History size={19} /></div><div><strong>View health history</strong><span>Previous assessments</span></div><ArrowRight size={17} /></button><button className="patient-action-card" onClick={onOpenTreatment}><div className="patient-action-icon"><FileText size={19} /></div><div><strong>View treatment plan</strong><span>Prescription and doctor instructions</span></div><ArrowRight size={17} /></button><button className="patient-action-card" onClick={onBookAppointment}><div className="patient-action-icon"><CalendarDays size={19} /></div><div><strong>Book doctor consultation</strong><span>Choose date and time</span></div><ArrowRight size={17} /></button><button className="patient-action-card" onClick={onOpenDoctor}><div className="patient-action-icon"><Stethoscope size={19} /></div><div><strong>Open doctor portal</strong><span>View your case</span></div><ArrowRight size={17} /></button></section>
        <section className="patient-panel patient-followup-card">
<div className="patient-followup-icon"><CalendarDays size={19} /></div>
<div><span className="patient-section-kicker">FOLLOW-UP & CONSULTATION</span>
{patient.followUpDate ? <><h3>Follow-up: {new Date(`${patient.followUpDate}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</h3><p>{patient.followUpStatus || "Scheduled"} • Review your treatment plan with the doctor.</p><button className="patient-text-button" onClick={onOpenTreatment}>View care plan <ArrowRight size={15}/></button></> : patient.appointment ? <><h3>{patient.appointment.date === "2026-09-08" ? "Tomorrow" : patient.appointment.displayDate}</h3><p>{patient.appointment.time} • {patient.appointment.doctor} • {patient.appointment.mode}</p><button className="patient-text-button" onClick={onOpenTreatment}>View care plan <ArrowRight size={15}/></button></> : <><h3>No follow-up scheduled</h3><p>Your doctor can add a follow-up date after consultation.</p><button className="patient-text-button" onClick={onBookAppointment}>Book appointment <ArrowRight size={15}/></button></>}
</div></section>
        <section className="patient-panel patient-history-panel"><div className="patient-panel-header"><div><span className="patient-section-kicker">RECENT HISTORY</span><h3>Previous visits</h3></div><FileText size={19} /></div>{history.length > 0 ? history.map((item) => <div className="patient-history-row" key={item.id}><div><strong>{item.chiefComplaint || "Health assessment"}</strong><span>{item.registeredAt || "Recent visit"}</span></div><span className={`patient-history-status ${(item.triage?.level || "moderate").toLowerCase()}`}>{item.triage?.level || "Review"}</span></div>) : <div className="patient-empty-history"><History size={24} /><p>Your completed assessments will appear here.</p></div>}<button className="patient-text-button" onClick={onViewHistory}>View all history <ArrowRight size={15} /></button></section>
      </aside></div>
    </div></div>
  );
}
